Migration Added on Server Startup
yushni/dictionary pull request #15
Opened 2020-08-12 15:54 UTC by borysej90

2020-08-13 14:43 UTC, yushni requested changes

2020-08-13 14:43 UTC, yushni commented on migration/migrate.go
> +	case "up":
я би рекомендував зробити то константою, бажано через іоту

2020-08-13 14:43 UTC, yushni commented on migration/migrate.go
> +func RunMigrate(upOrDown string) error {
Я би рекомендував передавати створити струкутуру, назвати її  RunOptions і туда запхати всі налаштування до міграцій. 
Наприклад, ми туда маємо передавати юзера, базу даних і хост де лежить, туда треба буде положити ше чи це ап чи даун

2020-08-13 14:43 UTC, yushni commented on migration/migrate.go
> +		err = m.Down()
а ше мені подобається варіант, якшо би Ап було б по дефолту. Бо зазвичай ми будемо їх апати, і тільки зрідка будемо їх, a кредли до бази даних, шоби були обовязкові. Подивись до такого варіанту https://www.sohamkamani.com/golang/options-pattern/

2020-08-15 16:03 UTC, yushni commented on api/restapi/configure_dictionary.go
>  	"github.com/go-openapi/swag"
goimports 

не забувай сортувати імпорти

2020-08-15 16:16 UTC, yushni commented on migration/migrate.go
> +	"github.com/golang-migrate/migrate/v4"
і тут

2020-08-15 16:16 UTC, yushni commented on migration/migrate.go
> +	if migration.user == "" || migration.password == "" {
а якшо на базі нема паролю ?

2020-08-15 16:16 UTC, yushni commented on migration/migrate.go
> +	if migration.user == "" || migration.password == "" {
Зроби для Бд окрему структуру з полями які треба для бд і передавай його в конструктор, ми форсаємо людей передавати конфіг для бд. А от таку штуку, як ап чи даун то опціонально

2020-08-15 16:16 UTC, yushni commented on migration/migrate.go
> +	if migration.user == "" || migration.password == "" {
(в цьому випадку то трохи оверхед, але я хотів би, аби ти знав таку штуку, як опціональні параметри)

2020-08-15 16:16 UTC, yushni commented on migration/migrate.go
> +	if migration.user == "" || migration.password == "" {
Тому я рекомендував би окрему структуру для бд і опціональну для даун чи ап

2020-08-20 17:21 UTC, yushni commented on migration/migrate.go
> +		if config.Host == "" {
зроби поля в конфігу приватними і додай конструктор 
не передавай завдання конффігу на міграцію не треба

2020-08-20 17:22 UTC, yushni commented on migration/migrate.go
> +func NewMigrate(opts ...MigrateOption) (*Migrate, error) {
конфіг бд має бути обовзковим 
(config DBConfig, opts ...MigrateOptions)

2020-08-20 17:26 UTC, yushni commented on migration/migrate.go
> +	address string
adress, userCreds i dbName - це тримає в собі конфіг, не передавй його відповідальність міграції

2020-08-20 17:26 UTC, yushni commented on migration/migrate.go
> +		"file://migration/migrations",
а цю штуку можеш додати в оптіонс і додати дефолтне значення

2020-08-21 16:39 UTC, yushni commented on migration/config.go
> +		cfg.userCreds = fmt.Sprintf("%s:%s", username, password[0])
Не дуже розумію, ти приймаєш масив паролів для того, шоб взяти з масиву тільки 1 елемент ?

2020-08-21 16:39 UTC, yushni commented on api/restapi/configure_dictionary.go
> +
Забери пустий рядок і ше раз відсортуй імпорти

2020-08-21 16:39 UTC, yushni commented on migration/config.go
> +// NewDBConfig returns DBConfig struct with properly formatted data you should
Коменти не пиши) 
Якшо добре назвеш методи, то краще не писати комента. Хіба би то був якийсь класний інтерфейс, який має особливості. А тут всьо ясно

2020-08-21 16:39 UTC, yushni commented on migration/config.go
> +type DBConfig struct {
ДБ конфіг додай метод String() і най він формує стрінгу для міграції

2020-08-21 16:39 UTC, yushni commented on migration/config.go
> +func NewDBConfig(address, database, username string, password ...string) DBConfig {
Приймай не адресу, приймай хост і додай метод сет порт і всьо. Упростиш свій код в 100 раз

2020-08-21 16:46 UTC, borysei commented on migration/config.go
> +		cfg.userCreds = fmt.Sprintf("%s:%s", username, password[0])
Я зробив опційний аргумент, щоб не створювати додатково метод, який додає пароль. Чи все-таки метод краще?

2020-08-24 07:00 UTC, yushni commented on api/restapi/configure_dictionary.go
дивись, для того аби гоіпортс добре працювало треба всі імпорти склеїти до купи і заустити команду. 
імпорти мають мати тільки одину пусту лінію, між внутрішніми пакетами і зовнішніми. 
Зроби ше раз

2020-08-24 07:00 UTC, yushni commented on api/restapi/configure_dictionary.go
> +	dbConfig := migration.NewDBConfig(
Цк вже не залежності рест апі, тому краще їх винести з цього пакету. Можеш створити в руті репи папочку app/dependencies.go - сюда запхай інітання  мігрейту 
i app/facilities/config.go - сюда запхай інітання конфігу

2020-08-24 07:00 UTC, yushni commented on migration/config.go
> +	cfg.address = fmt.Sprintf("%s:%s", host, defaultPostgresPort)
не комбайн їх, для чого ? Кожного разу на сеті ти мусиш розібрати його і потім знов зібрати... лишня робота. 
збережи окремо хост і порт, сетни по дефолту порт і якшо треба буде додати то пересетни його 




```suggestion
        cfg.port = 5432
        cfg.host = host  
```

2020-08-24 07:00 UTC, yushni commented on migration/config.go
> +	host := strings.Split(c.address, ":")[0]
```suggestion
     c.port = port
     
     return c
```

2020-08-24 07:00 UTC, yushni commented on migration/config.go
> +	username := strings.Split(c.userCreds, ":")[0]
тут то саме, не ускладнюй

2020-08-24 07:00 UTC, yushni commented on migration/config.go
> +func (c *DBConfig) String() string {
чого воно в тебе поінтером ?

2020-08-24 07:00 UTC, yushni commented on migration/config.go
> +// String generates Postgres database connection URI.
видаляй ті коменти, ітак ясно шо воно робить

2020-08-24 07:00 UTC, yushni commented on migration/migrate.go
> +type Migrate struct {
спочатку постав структуру, а потім конструктор, аби було видно зразу шо ти інітиш

2020-08-24 07:00 UTC, yushni commented on migration/migrate.go
> +	direction int
видаляй коменти і забирай пусті строки між полями
воно не дає ніякого +, а тільки засирає код 
тут і так очевидно, шо воно робить

2020-08-24 07:00 UTC, yushni commented on migration/migrate.go
> +	default:
чи можливий такий кейс ?

2020-08-24 07:00 UTC, yushni commented on migration/migrate.go
> +	_ "github.com/golang-migrate/migrate/v4/source/file"
migration/migrate.go:8:2: a blank import should be only in a main or test package, or have a comment justifying it (golint)
        _ "github.com/golang-migrate/migrate/v4/database/postgres"
        ^


пофіксай лінтер

2020-08-24 07:45 UTC, borysej90 commented on migration/migrate.go
> +	default:
`Default` може пригодиться, якщо вдруг хтось створить цю структуру не через конструктор

2020-08-26 05:32 UTC, yushni commented on app/dependencies.go
> +type IMigrate interface {
keep only migrate, get rid of I, it is not necessary

2020-08-26 05:33 UTC, yushni commented on app/facilities/db.go
> +	c.hasPassword = true
remove

2020-08-26 05:34 UTC, yushni commented on app/facilities/db.go
> +	if c.hasPassword {
it is unnecessary, you can check 
if c.password != "" {
 ....
 }

2020-08-26 05:36 UTC, yushni commented on app/facilities/db.go
> +	cfg := DBConfig{}
return DBConfig {
	host             host
	username    username
	dbName      database
       .......
}

2020-08-28 06:25 UTC, yushni commented on app/facilities/db.go
> +// DO NOT create DBConfig directly without constructor.
видали комент, то і так очевидно))

2020-08-29 13:58 UTC, yushni approved these changes

2020-09-15 19:01 UTC, yushni commented on app/facilities/config.go
> +	if pass, hasPass := os.LookupEnv("db_password"); hasPass {
Перевага LookupEnv nad Getenv в тому, шо ти можеш знати точно, чи засетана енв змінна чи не 
Тут ти не використовуєш того
Якшо вона не знайдена, ти лишаєш дефолтне значення типу, тобто то саме шо отримав би з os.Getenv тільки без додаткових провірок

2020-09-15 19:04 UTC, merged